### ISSUE TITLE
TBLIS has to be initialized

### ISSUE THREAD

**Issue by gustavojra** [mdav2/JuES.jl#25]
Trying to run JuES directly like:

> using JuES
> JuES.Input.run("input.dat")

raises an error

> ERROR: ArgumentError: NULL library handle
> Stacktrace:
>  [1] #dlsym#1 at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:54 [inlined]
>  [2] dlsym(::Ptr{Nothing}, ::Symbol) at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:54
>  [3] TBLIS.TTensor{Float64}(::Array{Float64,4}, ::Float64) at /Users/aroeira/.julia/packages/TBLIS/l7YMy/src/TTensor.jl:51
>  [4] TBLIS.TTensor{Float64}(::Array{Float64,4}) at /Users/aroeira/.julia/packages/TBLIS/l7YMy/src/TTensor.jl:26
>  [5] get_eri(::JuES.Wavefunction.Wfn{Float64}, ::String; notation::String, fcn::Int64) at /Users/aroeira/JuES/JuES.jl/src/Backend/IntegralTransformation.jl:74
>  [6] do_rccsd(::JuES.Wavefunction.Wfn{Float64}; kwargs::Base.Iterators.Pairs{Symbol,Integer,NTuple{5,Symbol},NamedTuple{(:quiet, :do_pT, :return_T, :doprint, :maxit),Tuple{Bool,Bool,Bool,Bool,Int64}}}) at /Users/aroeira/JuES/JuES.jl/src/CoupledCluster/AutoRCCSD.jl:239
>  [7] exec(::Dict{String,Any}) at /Users/aroeira/JuES/JuES.jl/src/Input/Input.jl:73
>  [8] run(::String) at /Users/aroeira/JuES/JuES.jl/src/Input/Input.jl:18
>  [9] top-level scope at REPL[4]:1
>  [10] eval(::Module, ::Any) at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [11] eval_user_input(::Any, ::REPL.REPLBackend) at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/julia/sys.dylib:?
>  [12] run_backend(::REPL.REPLBackend) at /Users/aroeira/.julia/packages/Revise/kqqw8/src/Revise.jl:1163
>  [13] top-level scope at REPL[1]:0

**Comment by mdav2** [comment]
Should be solved by [https://github.com/mdav2/TBLIS.jl/commit/73205b55f9eedd624eb9f646a70e35aa0b7b7c71](this)
